AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating upload and storage S3 buckets

Parameters:
  Environment:
    Type: String
    Description: Environment name for tagging and bucket prefix
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod

  UploadExpirationDays:
    Type: Number
    Description: Number of days after which objects in the upload bucket will be deleted
    Default: 7
    MinValue: 1
    MaxValue: 365

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${Environment}-uploads
      VersioningConfiguration:
        Status: Enabled
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldUploads
            Status: Enabled
            ExpirationInDays: !Ref UploadExpirationDays
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub ${Environment}-uploads
        - Key: Purpose
          Value: uploads

  UploadBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UploadBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceSSLOnly
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Sub arn:aws:s3:::${UploadBucket}
              - !Sub arn:aws:s3:::${UploadBucket}/*
            Condition:
              Bool:
                aws:SecureTransport: false

  StorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${Environment}-storage
      VersioningConfiguration:
        Status: Enabled
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 90
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 365
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub ${Environment}-storage
        - Key: Purpose
          Value: storage

  StorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StorageBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceSSLOnly
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Sub arn:aws:s3:::${StorageBucket}
              - !Sub arn:aws:s3:::${StorageBucket}/*
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  UploadBucketName:
    Description: Name of the upload S3 bucket
    Value: !Ref UploadBucket

  UploadBucketARN:
    Description: ARN of the upload S3 bucket
    Value: !GetAtt UploadBucket.Arn

  StorageBucketName:
    Description: Name of the storage S3 bucket
    Value: !Ref StorageBucket

  StorageBucketARN:
    Description: ARN of the storage S3 bucket
    Value: !GetAtt StorageBucket.Arn
Transform: AWS::Serverless-2016-10-31